# (C) 2026 GoodData Corporation
name: Create GitHub Release

on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: true
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release (e.g. v0.1.0)'
        type: string
        required: true

permissions:
  contents: write

jobs:
  github_release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate changelog
        id: changelog
        uses: requarks/changelog-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ inputs.tag }}
          writeToFile: false
          includeRefIssues: false
          useGitmojis: false

      - name: Create GitHub release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag }}
          body: ${{ steps.changelog.outputs.changes }}
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          make_latest: true
